### ISSUE TITLE
Feature Request : Add User-Agent header.

### ISSUE THREAD

**Issue by spankywetfish** [GhostManager/mythic_sync#7]
Add a `User-Agent` header to line 171 of `sync.py` to allow better distinction of actions in GW logs when troubleshooting .

e.g.
 ```
 headers = {"User-Agent": "Mythic_Sync", "Authorization": f"Bearer {GHOSTWRITER_API_KEY}", "Content-Type": "application/json"}
 ```

**Comment by chrismaddalena** [comment]
That's a great idea. I'll add that and get it into a release this week. I'll probably add to it to include a version number for additional identification.
